spring:
  application:
    name: itoken-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/kongyaohui/itoken-config.git
          search-paths: respo
          username: kongyaohui
          password: kyh828315
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/